### ISSUE TITLE
The Node-Module doesn't work properly with the latest node-red version

### ISSUE THREAD

**Issue by erkenes** [coldfire84/node-red-alexa-home-skill-v3-web#138]
**Describe the bug**
The Node-Module [node-red-contrib-alexa-smart-home](https://www.npmjs.com/package/node-red-contrib-alexa-smart-home) doesn't work with the latest Node-Red Version.

**To Reproduce**
Go to the Pallet Manager and search & install `node-red-contrib-alexa-smart-home`.

Put the Node `alexa smart home v3` into a flow. Add a new Account to the configuration.
Go back to the node and press the reload button to the right of the device list.

**Expected behavior**
That my devices are loaded into the list.

**Log Output**
```
TypeError: RED.warn is not a function
    at /root/.node-red/node_modules/node-red-contrib-alexa-smart-home/alexa.js:997:17
    at Layer.handle [as handle_request] (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at param (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:354:14)
    at param (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:410:3)
    at next (/root/.nvm/versions/node/v15.5.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
```

**Environment (please complete the following information):**
 - Node-RED node version: v1.2.6
 - Node-RED version: v15.5.0 (latest LTS)

**Comment by erkenes** [comment]
I can't find the repository for the Module (the link on the npm page doesn't work) but if I inspect the files in node_modules `RED.warn` is only in this red marked part:
![image](https://user-images.githubusercontent.com/8766722/103375941-a5823800-4adb-11eb-8429-cd9b234e8edb.png)

**Comment by erkenes** [comment]
Hmm after I added a new Account and refreshed the Device List the error was still there. After a deployment too.

Then I pressed the edit button for the Account first. After that I pressed "save" without a changing something.
At the end I just pressed the refresh button at the device list (without deploying first) and the list was refreshed without an error.


BUT `RED.warn()` still doesn't work so no warning message is shown.
