### ISSUE TITLE
No oAuth / no Linking possible 

### ISSUE THREAD

**Issue by diba78** [coldfire84/node-red-alexa-home-skill-v3-web#3]
Hi coldfire,

i got a second problem. the linking / oAuth is not possible. I connected to https:///admin/services - only a login with the mqtt user is posible. Then i go to the oauth section an create an new service. i put there the information from Alex Skill - Secret and Redirceting URLs. Service ID is 1 (same as in the alexa config).

First Info. An edit of the service is not possible.

When i am in the alexa app to active the skill it starts and open an url. then i got the folowing msg: internal Server error.

In the docker log from the webservice i got the following error.

[2018-10-30T22:04:06.154Z] [INFO] Checking OAuth redirectURI against defined service domain: https://alexa.amazon.co.jp/api/skill/link/MSXI125E5M8IR
[2018-10-30T22:04:06.154Z] [INFO] Checking OAuth redirectURI against defined service domain: https://layla.amazon.com/api/skill/link/MSXI125E5M8IR
[2018-10-30T22:04:06.154Z] [INFO] Checking OAuth redirectURI against defined service domain: https://pitangui.amazon.com/api/skill/link/MSXI125E5M8IR
Error: ERROR: Could not find service definition associated with redirectURI:
    at /usr/src/app/index.js:469:10
    at /usr/src/app/node_modules/mongoose/lib/model.js:4518:16
    at process.nextTick (/usr/src/app/node_modules/mongoose/lib/query.js:2579:28)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

have you any idea what i made wrong ?

Best regards

Dirk

**Comment by diba78** [comment]
Hi coldfire,

editing the service settings works now. After i configured only the domains and not the whole sting from the alexa home skill everything works fine.

Thanks a lot.

Best regards

Dirk
