### ISSUE TITLE
[OAuth Server] Valid AccessToken not found for user

### ISSUE THREAD

**Issue by GibbotauroSpaziale** [coldfire84/node-red-alexa-home-skill-v3-web#84]
I'm trying to deploy this system on my own because i need to implement a custom system to make work with another project.

I followed the guide but I'm getting the following error.

debug: [Oauth2] Exchange application:{ domains:
   [ 'pitangui.amazon.com',
     'alexa.amazon.co.jp',
     'layla.amazon.com' ],
  _id: 3e*******************4,
  title: 'Amazon',
  oauth_secret: '1234567890',
  oauth_id: 2,
  __v: 8 } {"timestamp":"2019-11-13T08:56:39.216Z"}
debug: [OAuth Server] Valid AccessToken not found for user:5dcbc011ed9fe3001792a45a

thank you in advance for the help!

**Comment by coldfire84** [comment]
I've reviewed the documentation and a recent element is missing, apologies.

Updated: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own#create-and-configure-the-alexa-skill

Essentially you need to enable `Send Alexa Events` in the Skill Config and provide the Client Id and Client Secret at Container runtime.

**Comment by coldfire84** [comment]
You'll need to disable and re-enable the skill in the Alexa App to re-generate the AccessToken on your account to enable the skill to send out of band events to Alexa (i.e. motion sensor state changes that can be used in Alexa Routines as Triggers).

**Comment by GibbotauroSpaziale** [comment]
Thank you for your quick reply! I've check and I've set the parameters correctly but I'm still getting this error when I try to link the skill to alexa from the app. I can't find what I made wrong.

**Comment by coldfire84** [comment]
_Completely_ misread your earlier post, although it flagged an error in the docs.

This is a debug/ informational log entry only, and effectively informs the developer. I've dropped a change in to improve logging to advise when a RefreshToken and AccessToken are successfully created.

Update your container (follow the docs) and check the logs for:
`[OAuth Server] Created RefreshToken for user`
`[OAuth Server] Created AccessToken for user:`

**Comment by GibbotauroSpaziale** [comment]
I'vd update the website and this is my output:

debug: [OAuth Server] Found valid AccessToken for user:5dcbc011ed9fe3001792a45a {"timestamp":"2019-11-15T08:07:28.942Z"}
debug: [OAuth Server] Found valid RefreshToken for user:5dcbc011ed9fe3001792a45a {"timestamp":"2019-11-15T08:07:28.945Z"}
debug: [OAuth Server] AccessToken sent expires_in: 476 {"timestamp":"2019-11-15T08:07:28.946Z"}
verbose: 54.240.197.84 - - [15/Nov/2019:08:07:28 +0000] "POST /auth/exchange HTTP/1.0" 200 - "-" "Apache-HttpClient/4.5.x (Java/1.8.0_232)"
 {"timestamp":"2019-11-15T08:07:28.948Z"}

**Comment by coldfire84** [comment]
OK, so it looks like the exchange / account linking has worked in that an access Token has been sent, meaning a Grant Code and Refresh Token have been created for the user through the account linking process.

What isn't working with your deployment?

**Comment by GibbotauroSpaziale** [comment]
When I authorize the alexa skill from the app, it will show the web page where I need to login to complete the authorization. At this point I click on authorize button and I get redirect to an amazon page that says: We were unable to link "App Name" at this time.

**Comment by coldfire84** [comment]
Looks like this *could* be SSL-certificate related:
https://forums.developer.amazon.com/questions/178157/we-were-unable-to-link-skill-name-at-this-time.html

Have you used LetsEncrypt for the SSL certificate/ NGINX to reverse proxy the NodeJS web app/API.

**Comment by GibbotauroSpaziale** [comment]
The cert is working. I find out that Cloud Watch dosn't show anything and maby could be for a missconfig here 

-v /var/docker/red/credentials:/root/.aws/credentials \

I don't think it should be /root/ but  /home/<user name>/

Also I don't understand what is the red in the docker folder, I hadn't create any red docker  container.
Another thing is that I don't understand what is:

resolver 127.0.0.11 ipv6=off;

in /var/docker/nginx/conf.d/nr-alexav3.cb-net.co.uk.conf I haven't installed any dns resolver.

Thankyou for your time!

**Comment by coldfire84** [comment]
I've cleaned up the wiki a little in relation to cloudwatch logging config: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own#configure-cloudwatch-logs

**Comment by coldfire84** [comment]
> I haven't installed any dns resolver.

Docker has it's [own DNS server](https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/) that we use to facilitate container-name based communication, rather than having to hard code IP addresses against each container. As long as you followed the wiki instructions you are using a "user-defined" Docker network, and this uses the 127.0.0.1 DNS server.

>  I don't understand what is:
resolver 127.0.0.11 ipv6=off;

From: http://nginx.org/en/docs/http/ngx_http_core_module.html

> By default, nginx will look up both IPv4 and IPv6 addresses while resolving. If looking up of IPv6 addresses is not desired, the ipv6=off parameter can be specified.

**Comment by coldfire84** [comment]
I'd also refresh your API container, the Docker Hub hosted images have been updated with the latest code.

**Comment by GibbotauroSpaziale** [comment]
Thank you for your answers! I have prune my docker than I recommitted all the commands. Now the nr-alexav3-web container keep restarting.

**Comment by coldfire84** [comment]
OK, can you share latest console logs please.

**Comment by GibbotauroSpaziale** [comment]
info: [Core] Connecting to MongoDB server: mongodb://mongodb:27017/users {"timestamp":"2019-11-29T10:17:10.468Z"}
info: [Core] Connecting to MongoDB... {"timestamp":"2019-11-29T10:17:10.469Z"}
info: [App] Using user-defined cookie secret {"timestamp":"2019-11-29T10:17:10.582Z"}
error: uncaughtException: Unexpected token b in JSON at position 5
SyntaxError: Unexpected token b in JSON at position 5
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/usr/src/app/functions/func-ghome.js:21:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/src/app/routes/default.js:26:19)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/src/app/app.js:129:19) {"error":{},"stack":"SyntaxError: Unexpected token b in JSON at position 5\n    at JSON.parse (<anonymous>)\n    at Object.<anonymous> (/usr/src/app/functions/func-ghome.js:21:14)\n    at Module._compile (internal/modules/cjs/loader.js:936:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)\n    at Module.load (internal/modules/cjs/loader.js:790:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:703:12)\n    at Module.require (internal/modules/cjs/loader.js:830:19)\n    at require (internal/modules/cjs/helpers.js:68:18)\n    at Object.<anonymous> (/usr/src/app/routes/default.js:26:19)\n    at Module._compile (internal/modules/cjs/loader.js:936:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)\n    at Module.load (internal/modules/cjs/loader.js:790:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:703:12)\n    at Module.require (internal/modules/cjs/loader.js:830:19)\n    at require (internal/modules/cjs/helpers.js:68:18)\n    at Object.<anonymous> (/usr/src/app/app.js:129:19)","exception":true,"date":"Fri Nov 29 2019 10:17:10 GMT+0000 (Coordinated Universal Time)","process":{"pid":18,"uid":0,"gid":0,"cwd":"/usr/src/app","execPath":"/usr/local/bin/node","version":"v12.10.0","argv":["/usr/local/bin/node","/usr/src/app/server.js"],"memoryUsage":{"rss":82870272,"heapTotal":58339328,"heapUsed":36150920,"external":20203999}},"os":{"loadavg":[1.43701171875,0.82177734375,0.32470703125],"uptime":121},"trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":14,"file":"/usr/src/app/functions/func-ghome.js","function":null,"line":21,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":936,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":947,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":790,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":703,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":830,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":68,"method":null,"native":false},{"column":19,"file":"/usr/src/app/routes/default.js","function":null,"line":26,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":936,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":947,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":790,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":703,"method":"_load","native":false},{"column":19,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":830,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":68,"method":null,"native":false},{"column":19,"file":"/usr/src/app/app.js","function":null,"line":129,"method":null,"native":false}],"timestamp":"2019-11-29T10:17:10.933Z"}
warn: [Logger] AWS credentials file does not exist at ~/.aws/credentials. Cludwatch logging disabled. {"timestamp":"2019-11-29T10:17:10.933Z"}
info: [Core] Connecting to Redis server... {"timestamp":"2019-11-29T10:17:10.948Z"}
info: [Core] Redis connection ready! {"timestamp":"2019-11-29T10:17:10.954Z"}
info: [Core] MongoDB connected! {"timestamp":"2019-11-29T10:17:11.024Z"}
info: [Core] MongoDB connection opened! {"timestamp":"2019-11-29T10:17:11.026Z"}
info: [App] Superuser MQTT account, mqttuser already exists {"timestamp":"2019-11-29T10:17:11.057Z"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-alexa-home-skill-v3@0.10.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-alexa-home-skill-v3@0.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-29T10_17_13_949Z-debug.log

**Comment by coldfire84** [comment]
`error: uncaughtException: Unexpected token b in JSON at position 5
SyntaxError: Unexpected token b in JSON at position 5
at JSON.parse ()
at Object. (/usr/src/app/functions/func-ghome.js:21:14)`

Thanks, I've change the way the JWT parsing works now, so that if it fails it'll warn you and the app will continue to function.

Please update your container image.

**Comment by GibbotauroSpaziale** [comment]
Thanks the website works. I get this error, mb I set somthing wrong:

docker attach nr-alexav3-web
debug: [Oauth2] Starting Auth for application:Amazon {"timestamp":"2019-11-29T17:38:04.824Z"}
info: [Oauth2] Checking OAuth redirectURI against defined service domain: https://pitangui.amazon.com {"timestamp":"2019-11-29T17:38:04.825Z"}
info: [Oauth2] Checking OAuth redirectURI against defined service domain: https://alexa.amazon.co.jp {"timestamp":"2019-11-29T17:38:04.825Z"}
info: [Oauth2] Checking OAuth redirectURI against defined service domain: https://layla.amazon.com {"timestamp":"2019-11-29T17:38:04.825Z"}
verbose: 62.19.157.151 - - [29/Nov/2019:17:38:04 +0000] "GET /auth/start?client_id=1&response_type=code&state=A2SAAEAEPuhiRL4GE5i7U90ON2a-OkB4N-IcHA1Lr3XrEXHtJsSYFpmw0LhAdU2lao7vVMjB5s_if4QF1NQH76MVs4q71DHCmq7kOsMLBmztU6RF8toFyjAftDyEc54GIlTyWM_DXvBGBIL1wy5luNlH5zYgXh9-geHfu3U3329E7uL8PGgesDFBJ4FSftkATj1R7czaBRxCLD54hDLY7fIXacKDB0P53WXfHTX3d8FwU8Rv_GItbD1YbOWqWEvfw1hN1PddmCyAgtklwvXd5pyL_3DlEYOwycSfxPpya_HGStktynRCTx3kb19_8xvew0QK74eALaFKqgvbKwTRK7IgMInFvP4k9aw_LFU_2-eZmrm0hbQ6mKN0IKCghyT5vyV4Z4lfCSGELKxIBRl6i5vGSljs0yX8R3hfkbTG7SdnENSOTdjYQmLTvan4GHT64jvIeOxoyI5DiZnTCvC6oX19_ziY4OFQdX-tR2tBHLM5gDgGP0sUQq0C_RftTpgbaNQZsTHn5ZGCFO5plKaBdXSqxG57aIiCKyhATiFiVsMNox88lJd78MScXVqGL5MOAayIBedcm7L6zJ0ViLea1RQUn_yKzIJnKyGpI3Zx_FKyMwtMe21dgtY2i6LVqVGk-NI0Eaec34pZcSSwwMqqA_G7DwSS5PgyQ&scope=access_devices+create_devices&redirect_uri=https%3A%2F%2Flayla.amazon.com%2Fapi%2Fskill%2Flink%2FM15Q5LA3VGFBDZ HTTP/1.0" 500 148 "-" "Mozilla/5.0 (Linux; Android 8.0.0; ASUS_Z01KS) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36"
 {"timestamp":"2019-11-29T17:38:04.826Z"}
Error: ERROR: Could not find service definition associated with redirectURI:
    at /usr/src/app/routes/auth.js:74:10

**Comment by coldfire84** [comment]
Can you confirm your OAuth service definition is correct, as per [OAuth Config]( https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own#configure-web-service-oauth) documentation.

It looks like you've incorrectly included `https://` in the domains.

**Comment by GibbotauroSpaziale** [comment]
Perfect! Thanks.
Now there still the ssl problem. I havn't do that part so idk what could be wrong, the certificate is valid. do you know how could I check why it dosn't work?

**Comment by coldfire84** [comment]
> Now there still the ssl problem.

I assume you mean [this](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/84#issuecomment-554302943)? I've outlined one way you can [request a Lets Encrypt certificate](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own#certificates) in the documentation.

There are other assumptions such as CDN (CloudFlare for example) configuration that are also pertinent with regards to SSL, and will vary (potentially *significantly*) by environment.

You can also engage Amazon ref Account Linking errors and they may be able to assist more in terms of why Amazon is rejecting the account linking.

It may also be worth checking the NGINX logs at the time of the account linking process to see what is passing through the proxy.

**Comment by GibbotauroSpaziale** [comment]
Solved! It was a stupid problem. In the Alexa Skill, under Permissions, Send Alexa Events must be set to off. Thank you for your help!
